all_the_skills = {
    "amazon": [
        "Jab", 
        "Power Strike", 
        "Poison Javelin", 
        "Fend", 
        "Lightning Bolt", 
        "Charged Strike", 
        "Plague Javelin", 
        "Molten Strike", 
        "Lightning Strike", 
        "Lightning Fury", 
        "Inner Sight", 
        "Lethal Strike", 
        "Phase Run", 
        "Dodge", 
        "Avoid", 
        "Penetrate", 
        "Evade", 
        "Decoy", 
        "Valkyrie", 
        "Pierce", 
        "Cold Arrow", 
        "Magic Arrow", 
        "Multiple Shot", 
        "Fire Arrow", 
        "Ice Arrow", 
        "Guided Arrow", 
        "Exploding Arrow", 
        "Strafe", 
        "Immolation Arrow", 
        "Freezing Arrow"
    ],     
    "assassin": [
        "Dragon Claw", 
        "Tiger Strike", 
        "Dragon Talon", 
        "Fists of Fire", 
        "Cobra Strike", 
        "Claws of Thunder", 
        "Dragon Flight", 
        "Blades of Ice", 
        "Claw Mastery", 
        "Psychic Hammer", 
        "Burst of Speed", 
        "Weapon Block", 
        "Cloak of Shadows", 
        "Fade", 
        "Shadow Warrior", 
        "Mind Blast", 
        "Venom", 
        "Shadow Master", 
        "Fire Blast", 
        "Shock Web", 
        "Blade Throw", 
        "Charged Bolt Sentry", 
        "Wake of Fire", 
        "Blade Fury", 
        "Lightning Sentry", 
        "Wake of Inferno", 
        "Death Sentry", 
        "Blade Shield"
    ],   
    "barbarian":[
        "Howl", 
        "Find Potion", 
        "Taunt", 
        "Shout", 
        "Find Item", 
        "Battle Cry", 
        "Battle Orders", 
        "Grim Ward", 
        "War Cry", 
        "Battle Command", 
        "Edged Weapon Mastery", 
        "Pole Weapon Mastery", 
        "Blunt Weapon Mastery", 
        "Thrown Weapon Mastery", 
        "Increased Stamina", 
        "Counter Attack", 
        "Iron Skin", 
        "Increased Speed", 
        "Puncture", 
        "Natural Resistance", 
        "Whirling Axes", 
        "Double Swing", 
        "Concentrate", 
        "Cleave", 
        "Frenzy", 
        "Stun", 
        "Leap Slam", 
        "Double Throw", 
        "Bash", 
        "Ethereal Throw", 
        "Whirlwind"
    ],
    "druid":[
        "Firestorm", 
        "Molten Boulder", 
        "Flame Dash", 
        "Arctic Blast", 
        "Fissure", 
        "Cyclone Armor", 
        "Twister", 
        "Volcano", 
        "Tornado", 
        "Armageddon", 
        "Hurricane", 
        "Werewolf", 
        "Lycanthropy", 
        "Werebear", 
        "Feral Rage", 
        "Maul", 
        "Rabies", 
        "Fire Claws", 
        "Hunger", 
        "Shock Wave", 
        "Fury", 
        "Raven", 
        "Poison Creeper", 
        "Heart of Wolverine", 
        "Summon Spirit Wolf", 
        "Carrion Vine", 
        "Oak Sage", 
        "Summon Dire Wolf", 
        "Solar Creeper", 
        "Spirit of Barbs", 
        "Summon Grizzly"
    ],
    "necromancer":[
        "Summon Mastery", 
        "Raise Skeleton Warrior", 
        "Bone Offering", 
        "Clay Golem", 
        "Flesh Offering", 
        "Raise Skeletal Mage", 
        "Blood Golem", 
        "Convocation", 
        "Iron Golem", 
        "Fire Golem", 
        "Revive", 
        "Deadly Poison", 
        "Teeth", 
        "Bone Armor", 
        "Corpse Explosion", 
        "Desecrate", 
        "Bone Spear", 
        "Bone Wall", 
        "Bone Spirit", 
        "Poison Nova", 
        "Amplify Damage", 
        "Dim Vision", 
        "Hemorrhage", 
        "Weaken", 
        "Iron Maiden", 
        "Terror", 
        "Confuse", 
        "Life Tap", 
        "Attract", 
        "Decrepify", 
        "Lower Resist"
    ],
    "paladin":[
        "Prayer", 
        "Resist Fire", 
        "Defiance", 
        "Resist Cold", 
        "Cleansing", 
        "Resist Lightning", 
        "Vigor", 
        "Meditation", 
        "Redemption", 
        "Salvation", 
        "Might", 
        "Holy Fire", 
        "Precision", 
        "Blessed Aim", 
        "Concentration", 
        "Holy Freeze", 
        "Holy Shock", 
        "Sanctuary", 
        "Fanaticism", 
        "Conviction", 
        "Sacrifice", 
        "Smite", 
        "Holy Bolt", 
        "Zeal", 
        "Charge", 
        "Vengeance", 
        "Blessed Hammer", 
        "Absolution", 
        "Holy Shield", 
        "Fist of the Heavens", 
        "Dashing Strike"
    ],
    "sorceress":[
        "Ice Bolt", 
        "Frigerate", 
        "Frost Nova", 
        "Ice Blast", 
        "Shiver Armor", 
        "Glacial Spike", 
        "Blizzard", 
        "Freezing Pulse", 
        "Chilling Armor", 
        "Frozen Orb", 
        "Cold Mastery", 
        "Charged Bolt", 
        "Static Field", 
        "Telekinesis", 
        "Nova", 
        "Lightning Surge", 
        "Chain Lightning", 
        "Teleport", 
        "Discharge", 
        "Thunder Storm", 
        "Energy Shield", 
        "Lightning Mastery", 
        "Fire Bolt", 
        "Warmth", 
        "Inferno", 
        "Immolate", 
        "Fire Ball", 
        "Fire Wall", 
        "Enflame", 
        "Meteor", 
        "Hydra", 
        "Fire Mastery"
    ]
}