name: Build and Deploy Test Site

on:
  workflow_dispatch:     # Allow manual trigger
  schedule:
    - cron: '0 4 * * 0'   # Every Sunday at 4am UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run fetch script
        run: python fetch_data.py

      - name: Run build script
        run: python build_pages.py

      - name: Check git status
        run: git status

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add hc_ladder.json index.html
          git commit -m "Auto-update data and HTML"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
